### ISSUE TITLE
Feature: project micro homepage

### ISSUE THREAD

**Issue by TomFreudenberg** [4commerce-technologies-AG/midi-smtp-server#24]
Checkout published micro homepage at:

https://4commerce-technologies-ag.github.io/midi-smtp-server/

**Comment by TomFreudenberg** [comment]
Hi  @gencer, @mwhobrey, @kaspergrubbe

if possible, it would be nice if you checkout the above microsite and leave your feedback.

Thanks
Tom

**Comment by gencer** [comment]
Hi @TomFreudenberg, It's flat and simple yet descriptive. I will be much better in time.

**Comment by mwhobrey** [comment]
Hey @TomFreudenberg ,

I like it. It's simple, clean and elegant with no nonsense. Only thing I would maybe change is moving the badges from the bottom "About the project" section to the top to make it more visible.

**Comment by TomFreudenberg** [comment]
Hey Gencer @gencer, hey Mike @mwhobrey 

thanks for your fast review and feedback.

@mwhobrey  Mike - I like your idea about the badges. Do you think we should double them (top and bottom) or just move to the top?

This is what it could like:

![grafik](https://user-images.githubusercontent.com/410087/47536228-4606bd00-d8bf-11e8-9f38-0b5d81368514.png)

Cheers
Tom

**Comment by mwhobrey** [comment]
Hey @TomFreudenberg,

I think that looks great there. As far as top/bottom/both, I don't see the harm in leaving it at the bottom too. It makes sense to me to have it in both places, now that I'm thinking about it. You get the benefit of having them up top where they get maximum visibility (and personally I think they look awesome where you have them in the screen shot), and then you also have the accessibility for a user who has scrolled through reading the page and then they don't have to go back up to click (plus it gives the bottom of the page some nice decor instead of just ending abruptly).

Thanks for your continued work. As soon as things slow down some at my 9-5, I would like to dig into some of the other help wanted issues.

Thanks again!
Mike

**Comment by TomFreudenberg** [comment]
Hi @mwhobrey thanks for comments - its online ;-)

Cheers
Tom
